module.exports = {
  hostels: [
    {
      name: "Aadi MahaLaxmi",
      adress: "Ammerpet",
      rooms: [
        { roomNumber: "101", capacity: 4 },
        { roomNumber: "102", capacity: 4 },
        { roomNumber: "103", capacity: 4 },
        { roomNumber: "104", capacity: 4 },
        { roomNumber: "105", capacity: 4 },
        { roomNumber: "106", capacity: 4 },
        { roomNumber: "107", capacity: 4 },
        { roomNumber: "108", capacity: 4 },
        { roomNumber: "201", capacity: 4 },
        { roomNumber: "202", capacity: 4 },
        { roomNumber: "203", capacity: 4 },
        { roomNumber: "204", capacity: 4 },
        { roomNumber: "205", capacity: 4 },
        { roomNumber: "206", capacity: 4 },
        { roomNumber: "207", capacity: 4 },
        { roomNumber: "208", capacity: 4 },
        { roomNumber: "301", capacity: 4 },
        { roomNumber: "302", capacity: 4 },
        { roomNumber: "303", capacity: 4 },
        { roomNumber: "304", capacity: 4 },
        { roomNumber: "305", capacity: 4 },
        { roomNumber: "306", capacity: 4 },
        { roomNumber: "307", capacity: 4 },
        { roomNumber: "308", capacity: 4 },
        { roomNumber: "401", capacity: 4 },
        { roomNumber: "402", capacity: 4 },
        { roomNumber: "403", capacity: 4 },
        { roomNumber: "404", capacity: 4 },
        { roomNumber: "405", capacity: 4 },
        { roomNumber: "406", capacity: 4 },
        { roomNumber: "407", capacity: 4 },
        { roomNumber: "408", capacity: 4 },
        { roomNumber: "501", capacity: 4 },
        { roomNumber: "502", capacity: 4 },
        { roomNumber: "503", capacity: 4 },
        { roomNumber: "504", capacity: 4 },
        { roomNumber: "505", capacity: 4 },
        { roomNumber: "506", capacity: 4 },
        { roomNumber: "507", capacity: 4 },
        { roomNumber: "508", capacity: 4 },
      ],
    },
  ],
};
